name: mozztask
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  dio: ^5.4.0
  firebase_database: ^10.4.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
